"""Generate documented synthetic ego-style videos from FreiHAND evaluation images.

This is not ground-truth ego video and is never used for quantitative scoring. It creates
short MP4s with affine camera motion, mild motion blur, and a moving translucent occluder,
so the qualitative rollout path can be exercised reproducibly without downloading a
license-gated external dataset.
"""
from __future__ import annotations

import argparse
from pathlib import Path

import cv2
import numpy as np


def make_clip(root: Path, out: Path, seed: int, seconds=10, fps=15):
    rng = np.random.default_rng(seed)
    ids = sorted((root / "evaluation" / "rgb").glob("*.jpg"))
    if not ids:
        raise FileNotFoundError(root / "evaluation/rgb")
    n = seconds * fps
    fourcc = cv2.VideoWriter_fourcc(*"mp4v")
    writer = cv2.VideoWriter(str(out), fourcc, fps, (224, 224))
    for t in range(n):
        p = ids[(seed * 97 + t * 7) % len(ids)]
        img = cv2.imread(str(p))
        img = cv2.resize(img, (224, 224))
        angle = 5.0 * np.sin(t / 11.0 + seed)
        scale = 1.0 + 0.035 * np.sin(t / 13.0)
        tx = 5.0 * np.sin(t / 17.0 + 0.4 * seed)
        ty = 4.0 * np.cos(t / 19.0)
        M = cv2.getRotationMatrix2D((112, 112), angle, scale)
        M[:, 2] += (tx, ty)
        img = cv2.warpAffine(img, M, (224, 224), borderMode=cv2.BORDER_REFLECT)
        if t % 3 == 0:
            img = cv2.GaussianBlur(img, (3, 3), 0.8)
        # simulated foreground occluder moving across lower image
        x = int(20 + 170 * ((t / max(1, n - 1) + 0.23 * seed) % 1.0))
        overlay = img.copy()
        cv2.ellipse(overlay, (x, 194), (38, 18), 0, 0, 360, (55, 70, 82), -1)
        img = cv2.addWeighted(overlay, 0.28, img, 0.72, 0)
        writer.write(img)
    writer.release()


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--root", default=str(Path.home() / "egohand_data/freihand"))
    p.add_argument("--out", default=str(Path(__file__).resolve().parents[1] / "data/egocentric_clips"))
    args = p.parse_args()
    out = Path(args.out); out.mkdir(parents=True, exist_ok=True)
    root = Path(args.root)
    make_clip(root, out / "clip_01_synthetic.mp4", seed=1)
    make_clip(root, out / "clip_02_synthetic.mp4", seed=2)
    (out / "README.md").write_text(
        "These are synthetic qualitative-only clips generated by data/synthesize_egocentric.py "
        "from FreiHAND eval images. They are not a substitute for real egocentric ground truth "
        "and are not included in quantitative accuracy metrics.\n"
    )
    print("wrote", out / "clip_01_synthetic.mp4", out / "clip_02_synthetic.mp4")


if __name__ == "__main__":
    main()